//! kkclaw SkillStore 复现测试
//!
//! 背景：kkclaw 的 SkillStore 使用 execute_params 向有 FTS 索引的 skills 表
//! 插入 Skill 数据。部分 Skill（prompts 含换行/管道符/代码块）失败。
//!
//! 运行：
//!   cargo test --test skill_store_params_tests -- --nocapture

use kkdb::types::Value;
use kkdb::vm::execute::{ExecResult, VM};

/// kkclaw skills 表的真实 DDL（完全一致）
fn create_skills_table(vm: &mut VM) {
    vm.execute_sql(
        "CREATE TABLE IF NOT EXISTS skills \
         (name TEXT PRIMARY KEY, desc TEXT, tags TEXT, prompts TEXT, embedding BLOB)",
    )
    .unwrap();

    vm.execute_sql(
        "CREATE FULLTEXT INDEX IF NOT EXISTS idx_skills_ft \
         ON skills (desc, tags, prompts)",
    )
    .unwrap();
}

// ─── Case 1: 基本 INSERT OR REPLACE（简单内容）────────────────────────────────

/// 验证 execute_params 能向有 FTS 索引的表写入简单 TEXT 值
#[test]
fn test_params_insert_simple_with_fts() {
    let mut vm = VM::new_memory();
    create_skills_table(&mut vm);

    let r = vm.execute_params(
        "INSERT OR REPLACE INTO skills (name, desc, tags, prompts) VALUES (?, ?, ?, ?)",
        &[
            Value::Text("langchain".into()),
            Value::Text("LangChain AI framework for building LLM apps".into()),
            Value::Text("llm agent python framework".into()),
            Value::Text("Use LangChain to build powerful AI pipelines.".into()),
        ],
    );
    assert!(r.is_ok(), "Simple INSERT with FTS failed: {r:?}");

    if let ExecResult::QueryResult { rows, .. } = vm.execute_sql("SELECT name FROM skills").unwrap()
    {
        assert_eq!(rows.len(), 1, "Expected 1 row");
    }
}

// ─── Case 2: prompts 包含换行符 ───────────────────────────────────────────────

/// 失败复现：prompts 包含 \n（多行 markdown）
#[test]
fn test_params_insert_multiline_prompts() {
    let mut vm = VM::new_memory();
    create_skills_table(&mut vm);

    let prompts = "# LangChain\n\nBuild LLM apps.\n\n## Usage\n\nImport and use chains.\n";

    let r = vm.execute_params(
        "INSERT OR REPLACE INTO skills (name, desc, tags, prompts) VALUES (?, ?, ?, ?)",
        &[
            Value::Text("langchain".into()),
            Value::Text("LangChain AI framework".into()),
            Value::Text("llm agent".into()),
            Value::Text(prompts.into()),
        ],
    );
    assert!(r.is_ok(), "INSERT with multiline prompts failed: {r:?}");
}

// ─── Case 3: prompts 包含管道符（markdown 表格）──────────────────────────────

/// 失败复现：prompts 包含 | 字符（markdown 表格）
#[test]
fn test_params_insert_pipe_chars_in_prompts() {
    let mut vm = VM::new_memory();
    create_skills_table(&mut vm);

    let prompts = "## Overview\n\n| Field | Value |\n|-------|-------|\n| Stars | 35787 |\n| Lang | Python |\n";

    let r = vm.execute_params(
        "INSERT OR REPLACE INTO skills (name, desc, tags, prompts) VALUES (?, ?, ?, ?)",
        &[
            Value::Text("agentgpt".into()),
            Value::Text("Autonomous AI Agents in browser".into()),
            Value::Text("agent autonomous".into()),
            Value::Text(prompts.into()),
        ],
    );
    assert!(r.is_ok(), "INSERT with pipe chars in prompts failed: {r:?}");
}

// ─── Case 4: prompts 包含代码块 ───────────────────────────────────────────────

/// 失败复现：prompts 包含 ``` 代码块（backtick fence）
#[test]
fn test_params_insert_code_block_in_prompts() {
    let mut vm = VM::new_memory();
    create_skills_table(&mut vm);

    let prompts = "## Usage\n\n```toml\n# SKILL.toml is already created.\n# Restart to activate.\n```\n\n## Notes\nAuto-generated.\n";

    let r = vm.execute_params(
        "INSERT OR REPLACE INTO skills (name, desc, tags, prompts) VALUES (?, ?, ?, ?)",
        &[
            Value::Text("AgentGPT".into()),
            Value::Text("> Auto-generated by **kkclaw-forge**.".into()),
            Value::Text("".into()),
            Value::Text(prompts.into()),
        ],
    );
    assert!(r.is_ok(), "INSERT with code block in prompts failed: {r:?}");
}

// ─── Case 5: 完整 AgentGPT 内容复现 ─────────────────────────────────────────

/// kkclaw 中实际触发失败的 AgentGPT 技能完整 prompts
#[test]
fn test_params_insert_agentgpt_real_content() {
    let mut vm = VM::new_memory();
    create_skills_table(&mut vm);

    let desc = "> Auto-generated by **kkclaw-forge**. Review before enabling in production.";
    let tags = "";
    let prompts = "\
# AgentGPT\n\
\n\
> Auto-generated by **kkclaw-forge**. Review before enabling in production.\n\
\n\
## Overview\n\
\n\
| Field | Value |\n\
|-------|-------|\n\
| Source | [https://github.com/reworkd/AgentGPT](https://github.com/reworkd/AgentGPT) |\n\
| Owner | reworkd |\n\
| Language | TypeScript |\n\
| Stars | 35787 |\n\
| License | yes |\n\
\n\
## Description\n\
\n\
🤖 Assemble, configure, and deploy autonomous AI Agents in your browser.\n\
\n\
## Usage\n\
\n\
```toml\n\
# kkclaw_data/skills/AgentGPT/SKILL.toml is already created.\n\
# To activate, ensure skill loading is enabled and restart KKClaw.\n\
```\n\
\n\
## Notes\n\
\n\
This manifest was auto-generated from repository metadata by kkclaw-forge.\n\
Inspect the source repository before enabling this skill in production.\n";

    let r = vm.execute_params(
        "INSERT OR REPLACE INTO skills (name, desc, tags, prompts) VALUES (?, ?, ?, ?)",
        &[
            Value::Text("AgentGPT".into()),
            Value::Text(desc.into()),
            Value::Text(tags.into()),
            Value::Text(prompts.into()),
        ],
    );
    assert!(r.is_ok(), "AgentGPT INSERT failed: {r:?}");

    // 更新同一行（INSERT OR REPLACE 去重）
    let r2 = vm.execute_params(
        "INSERT OR REPLACE INTO skills (name, desc, tags, prompts) VALUES (?, ?, ?, ?)",
        &[
            Value::Text("AgentGPT".into()),
            Value::Text("Updated desc.".into()),
            Value::Text("agent gpt autonomous".into()),
            Value::Text(prompts.into()),
        ],
    );
    assert!(
        r2.is_ok(),
        "AgentGPT second INSERT OR REPLACE (dedup) failed: {r2:?}"
    );

    // 只应有 1 行
    if let ExecResult::QueryResult { rows, .. } = vm.execute_sql("SELECT name FROM skills").unwrap()
    {
        assert_eq!(
            rows.len(),
            1,
            "Expected 1 row after dedup, got {}",
            rows.len()
        );
    }
}

// ─── Case 6: 批量 35 条（kkclaw 真实场景）────────────────────────────────────

/// kkclaw 启动时批量 sync 35 个 skills，全部应成功
#[test]
fn test_params_batch_35_skills() {
    let mut vm = VM::new_memory();
    create_skills_table(&mut vm);

    let skills = [
        ("langchain", "LangChain AI framework", "llm python agent", "Build AI apps with LangChain.\n## Features\n- Chains\n- Agents\n"),
        ("autogen", "AutoGen multi-agent framework", "agent microsoft", "AutoGen enables multi-agent conversations.\n| Role | Description |\n|------|-------------|\n| User | Human proxy |\n"),
        ("crewAI", "CrewAI role-based agents", "crew agent role", "CrewAI lets you create crews of agents.\n```python\ncrew = Crew(agents=[...])\n```\n"),
        ("dify", "Dify LLM app platform", "llm platform", "Dify is an open-source LLM app development platform.\n"),
        ("AgentGPT", "> Auto-generated by kkclaw-forge.", "", "# AgentGPT\n\n| Field | Value |\n|-------|-------|\n| Stars | 35787 |\n\n```toml\n# SKILL.toml created.\n```\n"),
    ];

    for (name, desc, tags, prompts) in &skills {
        let r = vm.execute_params(
            "INSERT OR REPLACE INTO skills (name, desc, tags, prompts) VALUES (?, ?, ?, ?)",
            &[
                Value::Text((*name).into()),
                Value::Text((*desc).into()),
                Value::Text((*tags).into()),
                Value::Text((*prompts).into()),
            ],
        );
        assert!(r.is_ok(), "Batch INSERT failed for skill '{name}': {r:?}");
    }

    if let ExecResult::QueryResult { rows, .. } = vm.execute_sql("SELECT name FROM skills").unwrap()
    {
        assert_eq!(rows.len(), skills.len(), "Expected {} rows", skills.len());
    }
}

// ─── Case 7: FTS 路由验证（column MATCH 语法）───────────────────────────────

/// 插入后 FTS index 正常工作（使用 KKDB 的 column MATCH 语法）
#[test]
fn test_params_insert_then_bm25_match() {
    let mut vm = VM::new_memory();
    create_skills_table(&mut vm);

    vm.execute_params(
        "INSERT OR REPLACE INTO skills (name, desc, tags, prompts) VALUES (?, ?, ?, ?)",
        &[
            Value::Text("langchain".into()),
            Value::Text("LangChain AI framework for LLM apps".into()),
            Value::Text("llm python agent framework".into()),
            Value::Text("Build powerful LLM-driven applications with LangChain.\n## Chains\nSequential tool calls.\n".into()),
        ],
    ).unwrap();

    vm.execute_params(
        "INSERT OR REPLACE INTO skills (name, desc, tags, prompts) VALUES (?, ?, ?, ?)",
        &[
            Value::Text("redis-skill".into()),
            Value::Text("Redis cache operations".into()),
            Value::Text("redis cache memory".into()),
            Value::Text("Use redis_get tool to query Redis cache.\n".into()),
        ],
    )
    .unwrap();

    // FTS query using KKDB's column MATCH syntax
    let result = vm.execute_sql("SELECT name FROM skills WHERE desc MATCH 'langchain' LIMIT 5");
    // If MATCH syntax is supported, verify the result; otherwise log what we got
    match result {
        Ok(ExecResult::QueryResult { rows, .. }) => {
            assert!(!rows.is_empty(), "FTS MATCH should find 'langchain'");
            assert_eq!(
                rows[0][0],
                Value::Text("langchain".into()),
                "First match should be 'langchain'"
            );
        }
        Ok(other) => panic!("Expected QueryResult, got {other:?}"),
        Err(e) => {
            // Record parse/eval error for diagnosis
            panic!("FTS MATCH query failed: {e:?}");
        }
    }
}
